### ISSUE TITLE
Missing lambda_function_payload.zip

### ISSUE THREAD

**Issue by z-matth** [awslabs/lambda-chef-node-cleanup#15]
Instructions state
"The included Terraform configuration files will create a Lambda function using a zip file named lambda_function_payload.zip in the parent directory (already present in this repository)"

It is not there. Must be created.

**Comment by dannenberg** [comment]
Under `Using This Example`: From the parent directory you can run zip -r lambda_function_payload.zip lambda/* which creates a zip file containing everything AWS Lambda needs to run the code. The name lambda_function_payload.zip is what the Terraform configuration expects the file to be named, so if you change it be sure to update terraform/main.tf as well.

This part of the README should probably be bumped up to before it discusses the existing zip and the mention of the zip already existing should be dropped.
