### ISSUE TITLE
DEBUG variable fails, needs to be lowercase

### ISSUE THREAD

**Issue by jmstallard** [awslabs/lambda-chef-node-cleanup#16]
change line 81 from 
if not debug:
to
if not DEBUG:

Also, I insist the only way I got this to work is with the following zip command:
cd lambda
zip -r ../lambda_function_payload.zip *

**Comment by jmstallard** [comment]
Ikes - correction - DEBUG variable fails, needs to be UPPER case!!

**Comment by vovandodev** [comment]
Thanks. Works for me!
