### ISSUE TITLE
AttributeError: 'bytes' object has no attribute 'read'

### ISSUE THREAD

**Issue by jabaughman** [awslabs/lambda-chef-node-cleanup#18]
Getting an attribute error:

START RequestId: d07ab175-56cf-11e7-b3a4-ad3d51c60f84 Version: $LATEST
[INFO]	2017-06-21T22:20:22.239Z	d07ab175-56cf-11e7-b3a4-ad3d51c60f84	====================================================
[INFO]	2017-06-21T22:20:22.239Z	d07ab175-56cf-11e7-b3a4-ad3d51c60f84	{'key3': 'value3', 'key2': 'value2', 'key1': 'value1'}
[INFO]	2017-06-21T22:20:22.239Z	d07ab175-56cf-11e7-b3a4-ad3d51c60f84	====================================================
[INFO]	2017-06-21T22:20:22.490Z	d07ab175-56cf-11e7-b3a4-ad3d51c60f84	Found credentials in environment variables.
[INFO]	2017-06-21T22:20:23.31Z	d07ab175-56cf-11e7-b3a4-ad3d51c60f84	Starting new HTTPS connection (1): kms.us-west-2.amazonaws.com
'bytes' object has no attribute 'read': AttributeError
Traceback (most recent call last):
  File "/var/task/main.py", line 66, in handle
    with chef.ChefAPI(CHEF_SERVER_URL, get_pem(), USERNAME, ssl_verify=VERIFY_SSL):
  File "/var/task/chef/api.py", line 63, in __init__
    key = Key(key)
  File "/var/task/chef/rsa.py", line 158, in __init__
    self.raw = fp.read()
AttributeError: 'bytes' object has no attribute 'read'

**Comment by seajoshc** [comment]
Closing out old issues.  Please re-open if the issue still persists.
