### ISSUE TITLE
aws lambda python urlib2 request error as Name or Service uknown.

### ISSUE THREAD

**Issue by usmanazhar** [awslabs/lambda-chef-node-cleanup#20]
Hi, 

I am trying to make http request call using both requests and urllib2 python libraries, but i am getting the error as "<urlopen error [Errno -2] Name or service not known>: URLError" 

Do we need to do any DNS configuration ? I am not able to see any such option in AWS console, the code below is sample code used to test it, and also trying to access google.com also gives same error. 

from __future__ import print_function

import json
import os
import urllib2
print('Loading function')
def lambda_handler(event, context):
    #print("Received event: " + json.dumps(event, indent=2))
    message = event['Records'][0]['Sns']['Message']
    print("From SNS: " + message)
    ami = getLatestAMI(os.environ['ACCOUNT_NAME'],os.environ['AWS_REGION'])
    print ("response..{}".format(ami))
    return message
    
def getLatestAMI(acct, reg):
    
    response2 = urllib2.urlopen('http://www.google.com')
    print (response2)
    data = response2.read()

**Comment by seajoshc** [comment]
No DNS configuration should be required.  Are you using a VPC for your Lambda function?
