### ISSUE TITLE
Not able to connect to the chef server URL.

### ISSUE THREAD

**Issue by anu11may** [awslabs/lambda-chef-node-cleanup#5]
PyChef Version : 0.2.3
```python
{
  "stackTrace": [
    [
      "/var/task/main.py",
      77,
      "my_handler",
      "if len(search) != 0:"
    ],
    [
      "/var/task/chef/search.py",
      82,
      "**len**",
      "return len(self.data['rows'])"
    ],
    [
      "/var/task/chef/search.py",
      59,
      "data",
      "self._data = self.api[self.url]"
    ],
    [
      "/var/task/chef/api.py",
      229,
      "__getitem__",
      "return self.api_request('GET', path)"
    ],
    [
      "/var/task/chef/api.py",
      225,
      "api_request",
      "response = self.request(method, path, headers, data)"
    ],
    [
      "/var/task/chef/api.py",
      208,
      "request",
      "response = self._request(method, self.url+path, data, dict((k.capitalize(), v) for k, v in request_headers.iteritems()))"
    ],
    [
      "/var/task/chef/api.py",
      195,
      "_request",
      "return urllib2.urlopen(request).read()"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      154,
      "urlopen",
      "return opener.open(url, data, timeout)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      431,
      "open",
      "response = self._open(req, data)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      449,
      "_open",
      "'_open', req)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      409,
      "_call_chain",
      "result = func(*args)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      1242,
      "https_open",
      "context=self._context)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      1199,
      "do_open",
      "raise URLError(err)"
    ]
  ],
  "errorType": "URLError",
  "errorMessage": "urlopen error [Errno -2] Name or service not known"
}
```

**Comment by anu11may** [comment]
Works on local. Seems problem related to DNS. 
[INFO]  2016-04-28T19:37:46.49Z ae135dbe-0d78-11e6-9ee0-b17829626650    Found credentials in environment variables.
[INFO]  2016-04-28T19:37:46.832Z    ae135dbe-0d78-11e6-9ee0-b17829626650    Starting new HTTPS connection (1): kms.us-east-1.amazonaws.com
urlopen error [Errno -2] Name or service not known: URLError

**Comment by seajoshc** [comment]
Hi there, can you clarify what "works on local" means please?  Is your Lambda in a VPC?  Are you able to share the FQDN of your Chef Server?  It sounds like the FQDN may not be reachable outside your network.

**Comment by anu11may** [comment]
I can run the lambda main.py on my local machine and it connects to chef server and cleans up the URL. In my local setup, I can just pass the instance id value. But it fails to run the same code in the AWS. I tried both the VPC setup for lambda and non VPC. It fails in both the setups. Checked security groups etc for the chef server running in AWS , thats seems ok too. I even launched the lambda function in the same VPC as chef server but that didn't help also.

**Comment by rorysavage77** [comment]
I am seeing this behavior also... when I am trying to connect to the VPC region

"errorMessage": "[Errno -2] Name or service not known"

**Comment by usmanazhar** [comment]
Hi, i am also trying to access the git hub url , it fails , however i tried to access google.com 

Still it fails with same error. 

{
  "stackTrace": [
    [
      "/var/task/lambda_function.py",
      16,
      "lambda_handler",
      "ami = getLatestAMI(os.environ['ACCOUNT_NAME'],os.environ['AWS_REGION'])"
    ],
    [
      "/var/task/lambda_function.py",
      24,
      "getLatestAMI",
      "response2 = urllib2.urlopen('http://www.google.com')"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      154,
      "urlopen",
      "return opener.open(url, data, timeout)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      429,
      "open",
      "response = self._open(req, data)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      447,
      "_open",
      "'_open', req)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      407,
      "_call_chain",
      "result = func(*args)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      1230,
      "http_open",
      "return self.do_open(httplib.HTTPConnection, req)"
    ],
    [
      "/usr/lib64/python2.7/urllib2.py",
      1200,
      "do_open",
      "raise URLError(err)"
    ]
  ],
  "errorType": "URLError",
  "errorMessage": "<urlopen error [Errno -2] Name or service not known>"
