### ISSUE TITLE
Issue with lambada func

### ISSUE THREAD

**Issue by innops** [awslabs/lambda-chef-node-cleanup#9]
Hi

Im not able to use this function, which Im not sure what exactly is the issue, I have checked everything based on https://aws.amazon.com/blogs/apn/automatically-delete-terminated-instances-in-chef-server-with-aws-lambda-and-cloudwatch-events/ but its not working

here is cloudwatch logs:

> [INFO]	2016-11-05T20:43:00.33Z	6b3aa31f-a398-11e6-****	====================================================
> [INFO]	2016-11-05T20:43:00.111Z	6b3aa31f-a398-11e6-be44-****	Found credentials in environment variables.
> [INFO]	2016-11-05T20:43:00.576Z	6b3aa31f-a398-11e6-be44-****	Starting new HTTPS connection (1): kms.us-east-1.amazonaws.com
> END RequestId: 6b3aa31f-a398-11e6-be44-*****
> REPORT RequestId: 6b3aa31f-a398-11e6-be44-*****	Duration: 5002.12 ms	Billed Duration: 5000 ms Memory Size: 128 MB	Max Memory Used: 43 MB	

Could you please help me?

Thanks

**Comment by matt-smith** [comment]
Hey @ali-karimkhani,

Did you get this up and running?  I managed to get it working yesterday with a few little changes to `main.py` and `local_config.py`. However I decided to not use terraform.

main.py
`line 41:  return event['detail']['EC2InstanceId']` 

local_config.py
`REGION= 'eu-west-1' # Change to region your AWS Lambda function is in`
`CHEF_SERVER_URL = 'https://my.chef.org/organizations/myorg'`
`USERNAME = 'myuseri'`
`VERIFY_SSL = True`

and finally added `encrypted_pem.txt` containing only the "CiphertextBlob" output form the KMS encrypt  command.

Hope this helps.
Matt
